# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
GET http://localhost:8080/chat
Accept: application/json
AUTH: e05e9c96-1576-4d4b-b376-e80da2661797

###

POST http://localhost:8080/login/token
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "login" : "amourety",
  "password": "di9cbdy4"
}

###